### ISSUE TITLE
need for a check_line_validity function

### ISSUE THREAD

**Issue by alexKleider** [LeamHall/bp_tracker#9]
Within the array_from_file function:
        # the following print statements are the closest we come to a
        # test of this function. Should we check that tuple members
        # are string representations of int, int, int, float?
i.e. should we add a check_line_validity function?

**Comment by alexKleider** [comment]
Modified array_from_file so that validity is checked within the function.
This closes issue_009

**Comment by LeamHall** [comment]
The nested method needs to be removed.
The parsing of useful_lines() should include the data validation in lines 92-101, and only useful lines added to the dataset.
- Others may put notes, or blank lines, or other stuff into the data file. All we need to do is deal with the valid data.
Add the numeric check for a range of 1-300 for integers. 
The "float/string" can be 0.0, if the data was entered but the datestamp unknown. So, no real validation on the datestamp.
if invalid lines are to be reported, it should only be if the "verbose" flag was set. Otherwise, as quiet as possible.

**Comment by LeamHall** [comment]
Updates look good, issue_009 merged into master.
